select * from customer;

--1) What is the total revenue generated by male vs. female customers?
select gender , sum(purchase_amount) as revenue from customer
group by gender 

--2) Which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount from customer where discount_applied='Yes' and purchase_amount >(select avg(purchase_amount) from customer)

--3) Which are the top 5 products with the highest average review rating?
select item_purchased ,ROUND(avg(review_rating::numeric),2) as "Average Product Rating" from customer 
group by item_purchased
order by avg(review_rating) desc
limit 5

--4)Compare the average Purchase amounts between standard and express shipping 
select shipping_type,ROUND(avg(purchase_amount),2) from customer
where shipping_type IN('Standard','Express')
group by shipping_type

--5) Do subscribed customers spend more? compare average apend and total revenue 
--between subscribers and non-subscribers 
select subscription_status,COUNT(customer_id) as total_customers,ROUND(avg(purchase_amount),2) as average_spend,sum(purchase_amount) as total_revenue
from customer
group by subscription_status
order by average_spend desc,total_revenue 

--6)Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
ROUND(100.00*SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 end )/Count(*),2) as discount_rate from customer
group by item_purchased
order by discount_rate desc
limit 5

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
WITH customer_type as (
select customer_id,previous_purchases ,
CASE
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment 
from customer
)
select  customer_segment , count(*) as "Number of Customers " FROM customer_type 
group by customer_segment 

--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts as (
	select item_purchased,
			category , 
			count(*) as number_of_orders, 
			ROW_NUMBER()OVER(PARTITION BY Category ORDER BY count(*) DESC) as item_rank
from customer
group by  category ,item_purchased 
)
select item_rank , category , item_purchased , number_of_orders from item_counts 
WHERE item_rank <=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, COUNT(*) as repeat_buyers from customer where previous_purchases > 5 
group by subscription_status 

--Q10. What is the revenue contribution of each age group? 
select age_group , sum(purchase_amount) as total_revenue from customer 
group by age_group
order by total_revenue desc
